name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Atualizado para v4
      
      - name: Set up Python
        uses: actions/setup-python@v5 # Atualizado para v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install customtkinter
          pip install python-docx
          pip install pyinstaller
      
      - name: Build with PyInstaller
        run: pyinstaller --onefile --noconsole --windowed upperTone.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4 # Atualizado para v4 (resolve o erro da imagem)
        with:
          name: UpperTone-Windows
          path: dist/*.exe
